export const orders = [
  {
    id: "#1001",
    customer: "محمد أحمد",
    phone: "01012345678",
    city: "القاهرة",
    address: "مدينة نصر",
    product: "Luna Necklace",
    items: 1,
    payment: "COD",
    shipping: "J&T",
    status: "Pending",
    tracking: "-",
  },
  {
    id: "#1002",
    customer: "سارة علي",
    phone: "01198765432",
    city: "الجيزة",
    address: "الدقي",
    product: "Rose Gold Ring",
    items: 2,
    payment: "Paid",
    shipping: "J&T",
    status: "Shipped",
    tracking: "JT45896321",
  },
  {
    id: "#1003",
    customer: "أحمد حسن",
    phone: "01255555555",
    city: "الإسكندرية",
    address: "سموحة",
    product: "Heart Bracelet",
    items: 3,
    payment: "COD",
    shipping: "J&T",
    status: "Delivered",
    tracking: "JT96521478",
  },
];